#!/bin/bash
set -e

[[ -x ~/bin/fmt-check ]] && (
    echo "--- Precommit: gofmt ---"
    ~/bin/fmt-check
)

# Disabled: Too noisy at the moment because of all the undocumented
# exported functions.
#echo "--- Precommit: lint ---"
#golint github.com/ThomasHabets/cmdg/...

echo "--- Precommit: govet ---"
go vet github.com/ThomasHabets/cmdg/...

echo "--- Precommit: unit tests ---"
go test github.com/ThomasHabets/cmdg/...
