name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Build binary
        run:
           go build ./cmd/cmdg
      - name: Vet
        run:
           go vet ./...
      - name: Test
        run:
           go test ./...
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v8
#        with:
#          version: v2.1
